name: Backend & Frontend Test

on:
  push:
    # This should disable running the workflow on tags, according to the
    # on.<push|pull_request>.<branches|tags> GitHub Actions docs.
    # cheers @ https://github.com/psycopg/psycopg/blob/5681de9c42f916d5b2436ad9c6f47b79c8aeaa12/.github/workflows/tests.yml#L4-L8
    branches:
      - "*"
  pull_request:
    branches: [main]

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker images
        run: docker buildx build --network=host -t archdev .
      - name: Build archpkgs
        run: docker run -v $(pwd):/build --rm archdev  /bin/bash -c "cd /build && makepkg -s"
      # - name: Create Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "*tar.gz"
      #     token: ${{ secrets.GITHUB_TOKEN }}
