name: Backend & Frontend Test


on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     tags: archdev
      #     # push: true
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      - name: Build docker images
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        run: |
          docker build  --network=host -t archdev --build-arg GPGKEY="$GPG_SIGNING_KEY" .
          chmod 777 ${{ runner.temp }}
          docker run -v ${{ runner.temp }}:/build --rm archdev /bin/bash -c "cp -r /home/builduser/* /build"


      - uses: actions/checkout@v3
        with:
          repository: dbadrian/archrepo
          ref: 'main'
          path: archrepo
          token:  ${{ secrets.ARCH_REPO_PUSH_TOKEN }}

      - name: push to arch db repo
        run: |
          cd $GITHUB_WORKSPACE/archrepo
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          cp ${{ runner.temp }}/*.pkg.tar.zst .
          cp ${{ runner.temp }}/*.pkg.tar.zst.sig .
          git add .
          git commit -m "Update package ${{ github.event.repository.name }}"
          git push origin main
          
      - name: Create Release
        uses: ncipollo/release-action@v1

        with:
          artifacts: "${{ runner.temp }}/*.pkg.tar.zst,${{ runner.temp }}/*.pkg.tar.zst.sig"
          # token: ${{ secrets.GITHUB_TOKEN }}
        

      # - name: Build archpkgs
      #   run: docker run -v $(pwd):/build --rm archdev /bin/bash -c "cp -r /home/builduser/* /build"
