name: Backend & Frontend Test

on:
  push:
    # This should disable running the workflow on tags, according to the
    # on.<push|pull_request>.<branches|tags> GitHub Actions docs.
    # cheers @ https://github.com/psycopg/psycopg/blob/5681de9c42f916d5b2436ad9c6f47b79c8aeaa12/.github/workflows/tests.yml#L4-L8
    branches:
      - "*"
  pull_request:
    branches: [main]

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    # services:
    #   registry:
    #     image: registry:2
    #     ports:
    #       - 5000:5000
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: archdev
          # push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Build docker images
      #   run: |
      #     docker buildx build --network=host -t archdev .
      #     docker run -v $(pwd):/build --rm archdev /bin/bash -c "cp -r /home/builduser/* /build"



      - name: Build archpkgs
        run: docker run -v $(pwd):/build --rm archdev /bin/bash -c "cp -r /home/builduser/* /build"
